name: Integration tests
on:
  - push
jobs:
  Integration-Test-Python:
    name: Integration Tests for Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [35, 36, 37, 38, 39]
    steps:
      - name: Install python prerequisites
        run: "sudo pip3 install docker-compose"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Perform integration tests for python version ${{ matrix.python_version }}
        run: "cd ${{ github.workspace }} && docker-compose run --rm integration_tests_py${{ matrix.python_version }}"
